workflows:
  # Workflow per iOS (AltStore - non firmato)
  ios-workflow:
    name: iOS Agriturismo Build
    instance_type: mac_mini_m2
    max_build_duration: 30
    
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
    
    scripts:
      - name: Set Flutter version
        script: |
          flutter --version
          flutter doctor
          
      - name: Get Flutter packages
        script: |
          flutter pub get
          
      - name: Build iOS (unsigned for AltStore)
        script: |
          flutter build ios --release --no-codesign
          
      - name: Create IPA
        script: |
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r ../../../agriturismo-app.ipa Payload
          
    artifacts:
      - agriturismo-app.ipa
      
  # Workflow per Android (APK non firmato per distribuzione diretta)
  android-workflow:
    name: Android Agriturismo Build
    instance_type: linux_x2
    max_build_duration: 30
    
    environment:
      flutter: stable
      android_signing:
        - agriturismo_keystore
      
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
    
    scripts:
      - name: Set Flutter version
        script: |
          flutter --version
          flutter doctor
          
      - name: Get Flutter packages
        script: |
          flutter pub get
          
      - name: Build Android APK (debug)
        script: |
          flutter build apk --debug
          
      - name: Build Android APK (release)
        script: |
          flutter build apk --release
          
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
      - build/app/outputs/flutter-apk/app-release.apk
