workflows:
  ios-workflow:
    name: iOS Agriturismo Build
    instance_type: mac_mini_m2
    max_build_duration: 30
    
    environment:
      flutter: 3.22.0
      xcode: 15.0
      cocoapods: default
      
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
    
    scripts:
      - name: Set Flutter version
        script: |
          flutter --version
          
      - name: Get Flutter packages
        script: |
          flutter pub get
          
      - name: Analyze code
        script: |
          flutter analyze
          
      - name: Build iOS (unsigned for AltStore)
        script: |
          flutter build ios --release --no-codesign
          
      - name: Create IPA
        script: |
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r ../../../agriturismo-app.ipa Payload
          
    artifacts:
      - agriturismo-app.ipa
